### ISSUE TITLE
Feature suggestion: Clickable dataset link

### ISSUE THREAD

**Issue by levyj** [anthonymoser/better_data_portal#1]
When you return the name of a dataset, make it a clickable link to the dataset (in addition to having a clickable link to download the CSV). I suspect a reasonably common use case will be, "Now that I know where those records exist, I want to look for similar records."

By the way, in case you do not know, a shorthand URL for any dataset (actually, any view, period) is:

https://data.cityofchicago.org/d/[4x4]

For example:

https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5

is equivalent to

https://data.cityofchicago.org/d/4ijn-s7e5

**Comment by anthonymoser** [comment]
Thanks, that's useful - I had considered this but didn't know about the /d/[id] formatting.
